name: Teste Simples

on:
  push:
    branches: [ main ]

jobs:
  exemplo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Mostrar arquivos
        run: ls -la

      - name: Mensagem 
        run: echo "Pipeline"
